- enabled running of ansible roles directly with --with-ansible-role arguments using an auto-generated localhost playbook - enabled support for installing XCode Command Line Tools on MacOS Catalina (10.15) and later. - ensured `brew cleanup` would run after brew upgrades - ensured ansible was run not as a system package, but as a pip package.  This guarantees consistency across platforms since the only system package pre-requisite is now python 3.6 or later. - cleaned up Travis CI configuration and assocaited build scripts. Added Ubuntu 16.04 to the build matrix.  Updated to latest MacOS High Sierra and Mojave versions.

diff --git a/cmd/run b/cmd/run
--- a/cmd/run
+++ b/cmd/run
@@ -17,6 +17,8 @@ strap::lib::import fs || source ../lib/fs.sh
 strap::lib::import os || source ../lib/os.sh
 strap::lib::import pkgmgr || source ../lib/pkgmgr.sh
 strap::lib::import pkg || source ../lib/pkg.sh
+strap::lib::import python || source ../lib/python.sh
+strap::lib::import ansible || source ../lib/ansible.sh
 
 STRAP_SCRIPT="${STRAP_SCRIPT:-}" && [[ -z "$STRAP_SCRIPT" ]] && echo "STRAP_SCRIPT is not set" && exit 1
 STRAP_HOME="${STRAP_HOME:-}" && [[ -z "$STRAP_HOME" ]] && echo "STRAP_HOME is not set" && exit 1
@@ -42,6 +44,7 @@ array_contains() {
   return 1
 }
 
+STRAP_ANSIBLE_ROLES=()
 STRAP_RUN_HOOK_PACKAGES=()
 # getopts loop logic from https://stackoverflow.com/a/28466267/407170
 declare args="${@:-}"
@@ -49,6 +52,13 @@ while getopts "p:-:" arg ${args}; do
   case "$arg" in
     - )  LONG_OPTARG="${OPTARG#*=}"
          case $OPTARG in
+           with-ansible-role=?* )
+             if [[ "${#STRAP_ANSIBLE_ROLES[@]}" -eq 0 ]] || \
+                ! array_contains "${STRAP_ANSIBLE_ROLES[@]}" "${LONG_OPTARG}" ]]; then # prevent adding the same package more than once
+               STRAP_ANSIBLE_ROLES+=("$LONG_OPTARG")
+             fi
+             ;;
+           with-ansible-role* )  echo "No arg for --$OPTARG option" >&2; exit 2 ;;
            with-hook-package=?* )
              if [[ "${#STRAP_RUN_HOOK_PACKAGES[@]}" -eq 0 ]] || \
                 ! array_contains "${STRAP_RUN_HOOK_PACKAGES[@]}" "${LONG_OPTARG}" ]]; then # prevent adding the same package more than once
@@ -64,6 +74,12 @@ while getopts "p:-:" arg ${args}; do
 done
 shift $((OPTIND-1)) # remove parsed options and args from $@ list
 #echo "packages: ${STRAP_RUN_HOOK_PACKAGES[@]}"
+
+# currently ansible roles and hook packages together are incompatible:
+if [[ "${#STRAP_ANSIBLE_ROLES[@]}" -gt 0 && "${#STRAP_RUN_HOOK_PACKAGES[@]}" -gt 0 ]]; then
+  echo "--with-ansible-role and --with-hook-package arguments cannot be used together.  Use either." >&2
+  exit 2
+fi
 
 cleanup() {
   set +e
@@ -184,16 +200,21 @@ strap::ok
 #############################################################
 
 strap::bot 'Package Manager'
-
 strap::pkgmgr::init
+
+#############################################################
+# Python & Pip
+#############################################################
+
+strap::bot 'Python & Pip'
+strap::python::install
 
 #############################################################
 # Ansible
 #############################################################
 
 strap::bot 'Ansible'
-
-strap::pkgmgr::pkg::ensure ansible
+strap::ansible::install
 
 #############################################################
 # Git & GitHub:
@@ -217,12 +238,6 @@ if [[ "$(strap::pkgmgr::id)" == 'yum' ]]; then
     sudo yum -y erase git >/dev/null 2>&1 || true
     strap::ok
   fi
-#  git_exe_path="$(git command -v 2>/dev/null || true)"
-#  if [[ -n "$git_exe_path" ]]; then # git is installed.  See if it came from git2u, which is our required package
-#    if ! rpm -qf "$git_exe_path" | grep git2u >/dev/null 2>&1; then
-#      #uninstall incompatible
-#    fi
-#  fi
 fi
 strap::pkgmgr::pkg::ensure "$git_package_name"
 
@@ -330,12 +345,14 @@ if [[ "${#STRAP_RUN_HOOK_PACKAGES[@]}" -gt 0 ]]; then
 
   strap::bot "Run Hook Packages"
 
-  # We use yq or python yaml (whichever is available) to convert yaml to json and then use jq to read package metadata
-  if strap::os::is_mac; then
-    strap::pkgmgr::pkg::ensure yq
-  else
-    strap::pkgmgr::pkg::ensure pyyaml
-  fi
+  # Ensure pyyaml is available so we can read strap package.yml metadata files:
+  strap::running "Ensuring strap virtualenv pyyaml"
+  set +e
+  output="$(python -m pip install --upgrade pyyaml 2>&1)"
+  retval="$?"
+  set -e
+  [[ "${retval}" -eq 0 ]] || strap::abort "Error: ${output}"
+  strap::ok
 
   # ensure packages exist, or download and are valid:
   for package_id in "${STRAP_RUN_HOOK_PACKAGES[@]}"; do
@@ -358,6 +375,9 @@ if [[ "${#STRAP_RUN_HOOK_PACKAGES[@]}" -gt 0 ]]; then
   done
   unset STRAP_HOOK_PACKAGE_ID STRAP_HOOK_PACKAGE_DIR
 
+elif [[ "${#STRAP_ANSIBLE_ROLES[@]}" -gt 0 ]]; then
+  strap::bot "Run Ansible Roles"
+  strap::ansible::roles::run "${STRAP_ANSIBLE_ROLES[@]}"
 fi
 
 # make config/state a little more secure, just in case:
