added --with-hook-package support to run command

diff --git a/cmd/run b/cmd/run
--- a/cmd/run
+++ b/cmd/run
@@ -14,6 +14,7 @@ strap::lib::import io || source ../lib/io.sh
 strap::lib::import logging || source ../lib/logging.sh
 strap::lib::import sudo || source ../lib/sudo.sh
 strap::lib::import fs || source ../lib/fs.sh
+strap::lib::import pkg || source ../lib/pkg.sh
 
 STRAP_DEBUG="${STRAP_DEBUG:-}"
 STRAP_SCRIPT="${STRAP_SCRIPT:-}" && [[ -z "$STRAP_SCRIPT" ]] && echo "STRAP_SCRIPT is not set" && exit 1
@@ -29,6 +30,31 @@ STRAP_QUIET_FLAG="-q"
 Q="$STRAP_QUIET_FLAG"
 
 STRAP_ISSUES_URL="https://github.com/ultimatedotfiles/strap/issues/new"
+
+STRAP_RUN_PACKAGES=()
+# getopts loop logic from https://stackoverflow.com/a/28466267/407170
+while getopts "p:-:" arg ${@:-}; do
+  case "$arg" in
+    #a )  ARG_A=true ;;
+    #p )  PLUGINS="$OPTARG" ;;
+    #c )  ARG_C=true ;;
+    - )  LONG_OPTARG="${OPTARG#*=}"
+         case $OPTARG in
+           with-hook-package=?* )  STRAP_RUN_PACKAGES+=("$LONG_OPTARG") ;;
+           with-hook-package*   )  echo "No arg for --$OPTARG option" >&2; exit 2 ;;
+           #alpha    )  ARG_A=true ;;
+           #bravo=?* )  ARG_B="$LONG_OPTARG" ;;
+           #bravo*   )  echo "No arg for --$OPTARG option" >&2; exit 2 ;;
+           #charlie  )  ARG_C=true ;;
+           #alpha* | charlie* )
+           #            echo "No arg allowed for --$OPTARG option" >&2; exit 2 ;;
+           '' )        break ;; # "--" terminates argument processing
+           * )         echo "Illegal option --$OPTARG" >&2; exit 2 ;;
+         esac ;;
+    \? ) exit 2 ;;  # getopts already reported the illegal option
+  esac
+done
+shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
 # Are we running interactive?
 STRAP_INTERACTIVE='' # assume not interactive by default
@@ -458,6 +484,33 @@ strap::ok
 # which GitHub does not store in its JSON, so any equality comparison would fail)
 ssh_pub_key_contents="$(cat $ssh_pub_key | awk '{print $1 " " $2}')"
 strap::github::api::user::keys::ensure "$github_token" "$ssh_pub_key_contents"
+
+#############################################################
+# Run Hook Packages:
+#############################################################
+if [[ -n "$STRAP_RUN_PACKAGES" ]]; then
+
+  strap::bot "Run Hook Packages"
+
+  strap::brew::ensure yq
+
+  # ensure packages exist, or download and are valid:
+  for package_id in "${STRAP_RUN_PACKAGES[@]}"; do
+    strap::pkg::ensure "$package_id"
+    strap::pkg::hook::path "$package_id" run >/dev/null # validates the package automatically
+  done
+
+  for package_id in "${STRAP_RUN_PACKAGES[@]}"; do
+    dir="$(strap::pkg::id::dir "$package_id")"
+    file="$(strap::pkg::hook::path "$package_id" run)"
+
+    if ! bash "$file"; then
+      strap::abort "Unable to execute package $package_id hook $file"
+    fi
+  done
+
+fi
+
 
 # make config/state a little more secure, just in case:
 chmod -R go-rwx "$STRAP_USER_HOME"
